srun: pyxis: skipping duplicate mount entry: /home/lmcafee /home/lmcafee x-create=auto,rbind,rw
pyxis: importing docker image ...
INFO:wrapper: Tasks on this node: 1
INFO:wrapper: Local rank: 0
ERROR:wrapper: Unable to process env var assignment: IVF4096_HNSW32
Traceback (most recent call last):
  File "/home/dcg-adlr-lmcafee-output/logs/UnspecifiedName_20220608-092208/wrapper_scripts/common/exec_and_report_v2.py", line 1216, in <module>
    main(sys.argv[1:])
  File "/home/dcg-adlr-lmcafee-output/logs/UnspecifiedName_20220608-092208/wrapper_scripts/common/exec_and_report_v2.py", line 927, in main
    set_env( varlist )
  File "/home/dcg-adlr-lmcafee-output/logs/UnspecifiedName_20220608-092208/wrapper_scripts/common/exec_and_report_v2.py", line 569, in set_env
    assert len(parts)==2, "Unable to process env var assignment: " + item
AssertionError: Unable to process env var assignment: IVF4096_HNSW32
srun: error: rno1-m02-f04-dgx2h-088: task 0: Exited with exit code 2
srun: Terminating job step 462922.0
Sbatch done waiting for srun completion. exit status was 2
Will check if need to submit the next job on host rno1-m02-f04-dgx2h-088
No autoresume requested
submit_next exit status was 2
